### ISSUE TITLE
Typescript Errors for example RBAC*

### ISSUE THREAD

**Issue by F1r3Hydr4nt** [imjulianeral/next-shield#17]
Hello,

Thanks for the great solution!

I am just wondering if every private route necessarily needs to be accessed via the defined 'accessRoute' (which in your examples is'/private') ?

Thanks again

**Comment by F1r3Hydr4nt** [comment]
Nevermind, it seems that is not actually the case

**Comment by F1r3Hydr4nt** [comment]
The [example code](https://imjulianeral.github.io/next-shield/docs/tutorial-extras/RBAC) for RBAC does not seem to be working however.

![image](https://user-images.githubusercontent.com/3375175/180317570-3ecdc27b-49f3-4c1c-914b-7b1ace4352df.png)

**Comment by F1r3Hydr4nt** [comment]
![Screenshot from 2022-07-21 23-29-21](https://user-images.githubusercontent.com/3375175/180325788-54f40c69-db47-4208-8f5d-2ef78edd82bd.png)
I mean, that **is** a string[], what could I be doing wrong?

**Comment by F1r3Hydr4nt** [comment]
I needed to declare the types:
```
const publicRoutes:   string[] = ['/', '/login', '/register', '/resources'];
const hybridRoutes:   string[] = ['/marketplace', '/storefront'];
```

**Comment by Ashkumar7** [comment]
> I needed to declare the types:
> ```
> const publicRoutes:   string[] = ['/', '/login', '/register', '/resources'];
> const hybridRoutes:   string[] = ['/marketplace', '/storefront'];
> ```

Thats strange.. typescript should have inferred it automatically
